#!/usr/bin/python3 -W ignore::DeprecationWarning
# -*- coding:utf8 -*-
from Answering import sentence_processing
from Answering import answer_generating

import sys

# Import our modules from /modules
sys.path.append("modules")


def answer(question):
    """
    :param question:
    :param word_log_inverse_freq:
    :return:
    """
    # TODO: reformat the question into a sentence
    question_reformat = question
    best_sentence = sentence_processing.find_best_candidate(question_reformat)
    # print(question, best_sentence)
    answer_generating.printAnswer(question, best_sentence)


if __name__ == '__main__':
    article_file_name = sys.argv[1]
    question_file_name = sys.argv[2]
    #article_file_name = '../data/set1/a6.txt'
    #question_file_name = '../question_set1_a1.txt'

    #question_file_name = '../test_questions.txt'
    try:
        question_list = open(question_file_name, encoding='utf8').read().split("\n")
    except:
        question_list = ['Did he go to CMU?']
    sentence_processing.cal_log_inverse_sentence_fre(article_file_name)
    for q in question_list:
        try:
            answer(q)
        except:
            print('Yes')