#!/usr/bin/python3 -W ignore::DeprecationWarning
# -*- coding:utf8 -*-
import sys
import spacy
import re
import codecs


if __name__ == "__main__":
    input_file = sys.argv[1]
    question_file = sys.argv[2]

    with open(question_file, 'r') as f:
        count = 0
        for line in f:
            count += 1
            print('A'+str(count))
